### ISSUE TITLE
App crashing when data is not being fetched for a certain amount of time.

### ISSUE THREAD

**Issue by subhav13** [openMF/mobile-wallet#1097]
**Summary:**

Sometimes when the progress bar keeps running due to data not being fetched for any reasons it crashes the app with the below details :
   --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobilewallet.mifospay, PID: 2867
    java.lang.IllegalStateException: progressBar must not be null
        at org.mifos.mobilewallet.mifospay.standinginstruction.ui.SIFragment.showStateView(SIFragment.kt:107)
        at org.mifos.mobilewallet.mifospay.standinginstruction.presenter.StandingInstructionsPresenter$getAllSI$1.onError(StandingInstructionsPresenter.kt:46)
        at org.mifos.mobilewallet.core.base.UseCaseThreadPoolScheduler$2.run(UseCaseThreadPoolScheduler.java:54)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Steps to reproduce:**

There will be an instance when data is being fetched for a certain amount of time than usual but didn't fetched and results in a crash.

**Expected behavior:**

Show a correct toast of why data is not being fetched from the servers.

**Observed behavior:**

App crashing 

**Device and Android version:**

Android emulator: pixel 3A XL, API 28
Physical Device: Samsung Galaxy A10, android 9 version

**Comment by deepak-prajapatii** [comment]
@subhav13 @Nayan @siebrand @vorburger @vishwasbabu Can I work on this issue?

**Comment by therajanmaurya** [comment]
Fixed, Does not exist anymore.
