### ISSUE TITLE
App crashes when null amount submitted in MerchantTransferActivity

### ISSUE THREAD

**Issue by singaltanmay** [openMF/mobile-wallet#794]
**Summary:**

Due to no null check taking place before converting a String to a Double, the app crashes when the submit button is clicked.

**Steps to reproduce:**

In MerchantTransferActivity press the Submit button without entering any amount.

**Expected behavior:**

Prompt the user to enter an amount.

**Observed behavior:**

The app crashes. Logcat : 
```

2020-03-07 19:13:13.964 3325-3325/org.mifos.mobilewallet.mifospay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobilewallet.mifospay, PID: 3325
    java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at org.mifos.mobilewallet.mifospay.merchants.ui.MerchantTransferActivity.makeTransaction(MerchantTransferActivity.java:146)
        at org.mifos.mobilewallet.mifospay.merchants.ui.MerchantTransferActivity_ViewBinding$1.doClick(MerchantTransferActivity_ViewBinding.java:45)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
**Device and Android version:**

Android Studio Emulator API 29

**Comment by dubeyaayush07** [comment]
duplicate #757 please check before submitting a new issue
