### ISSUE TITLE
FINERACT-726

### ISSUE THREAD

**Issue by vodera** [openMF/mobile-wallet#874]
**Summary:**
"Invalid JSON in BODY (no longer URL param; see FINERACT-726) of POST to /authentication: ",

**Steps to reproduce:**

Pull from the latest sources in the dev branch and run the code.

**Expected behavior:**
Authentication to be successful

**Observed behavior:**

ERROR: "Invalid JSON in BODY (no longer URL param; see FINERACT-726) of POST to /authentication: ", "path":"/fineract-provider/api/v1/self/authentication"

**Comment by Bhavnaharitsa** [comment]
@vodera Unfortunately, I am not able to reproduce the error. Could you please attach a screenshot of it?

**Comment by vodera** [comment]
![FINERACT-726](https://user-images.githubusercontent.com/14106148/79236096-2d081800-7e75-11ea-85c7-221edfaf84d1.PNG)


This is a screenshot of the logs, when trying to login. After investigating the issue further i found this article on FINERACT-726
https://issues.apache.org/jira/browse/FINERACT-726

**Comment by afk11** [comment]
It looks like the FINERACT-726 changes first occurred apache/fineract a93a6b848732141494b2f0cc11de346623bc23e6 on 1 April 2020 and with a subsequent check producing "Invalid JSON" exception in June 2020

https://github.com/apache/fineract/blob/db04976f4f32c6252ead264d0d61d95717bc1cdf/fineract-provider/src/main/java/org/apache/fineract/infrastructure/security/api/AuthenticationApiResource.java#L107-L115

**Comment by afk11** [comment]
```
20-Sep-2021 17:15:45.060 SEVERE [https-jsse-nio-443-exec-17] com.sun.jersey.spi.container.ContainerResponse.mapMappableContainerException The RuntimeException coul
d not be mapped to a response, re-throwing to the HTTP container                                                                                                                                                   
        java.lang.IllegalArgumentException: Invalid JSON in BODY (no longer URL param; see FINERACT-726) of POST to /authentication:                                                                               
                at org.apache.fineract.infrastructure.security.api.AuthenticationApiResource.authenticate(AuthenticationApiResource.java:105)                                                                      
                at org.apache.fineract.portfolio.self.security.api.SelfAuthenticationApiResource.authenticate(SelfAuthenticationApiResource.java:60)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
                at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
                at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
                at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
                at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
                at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
                at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
                at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)

```

**Comment by therajanmaurya** [comment]
Fixed, Authentication working
